### ISSUE TITLE
Node cannot find module mongorito (#122)

### ISSUE THREAD

**Issue by Alex-iFactory** [vdemedes/mongorito#123]
@vdemedes the issue #122 I can confirm,

With node `v6.2.0` mongorito is not found, however exists in node_modules. When I install mongorito@2.0.0 it is found.

I have only tested with `2.2.x` (not found) and `2.0.0` (found).

Cheers

**Comment by ainesophaur** [comment]
I had to do a reinstall of my node_modules and Im experiencing this issue too. It looks like the index.js referenced in the files section of package.json is missing

If you create an index.js file inside of the node_modules/mongorito file, put the following inside

```javascript
module.exports = require('./lib/mongorito');
```

For the repo maintainer, below is the package.json that NPM resolved when I installed mongorito.

```json
{
  "name": "mongorito",
  "version": "2.1.0",
  "description": "ES6 generator-based MongoDB ODM. It rocks.",
  "author": {
    "name": "Vadim Demedes",
    "email": "vdemedes@gmail.com"
  },
  "dependencies": {
    "bluebird": "^3.3.1",
    "class-extend": "^0.1.2",
    "clone": "^1.0.2",
    "co": "^4.6.0",
    "get-value": "^2.0.3",
    "is-generator-fn": "^1.0.0",
    "is_js": "^0.7.4",
    "lodash.result": "^4.2.0",
    "mongodb": "^2.0.48",
    "object-assign": "^4.0.1",
    "pluralize": "^1.2.1",
    "set-value": "^0.2.0"
  },
  "devDependencies": {
    "ava": "^0.12.0",
    "chance": "^0.8.0",
    "coveralls": "^2.11.4",
    "eslint-config-vdemedes": "^1.0.2",
    "nyc": "^5.0.0",
    "xo": "^0.12.1"
  },
  "files": [
    "index.js",
    "util",
    "lib"
  ],
  "scripts": {
    "test": "xo && nyc ava --serial",
    "coveralls": "nyc report --reporter=text-lcov | coveralls"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/vdemedes/mongorito.git"
  },
  "keywords": [
    "mongo",
    "mongodb",
    "co-mongo",
    "co-mongodb",
    "orm",
    "odm",
    "es6"
  ],
  "license": "MIT",
  "xo": {
    "extends": "vdemedes",
    "esnext": true,
    "env": [
      "node",
      "mocha"
    ],
    "ignore": [
      "examples/*.js"
    ],
    "rules": {
      "prefer-arrow-callback": 0,
      "prefer-spread": 0
    }
  },
  "gitHead": "5d89e612913dc11209fe1623e4ced1b36cced856",
  "bugs": {
    "url": "https://github.com/vdemedes/mongorito/issues"
  },
  "homepage": "https://github.com/vdemedes/mongorito#readme",
  "_id": "mongorito@2.1.0",
  "_shasum": "a93c1b6e32ed814782a7998ad4b669b2e3d3957e",
  "_from": "mongorito@>=2.1.0 <3.0.0",
  "_npmVersion": "3.8.6",
  "_nodeVersion": "6.1.0",
  "_npmUser": {
    "name": "vdemedes",
    "email": "vdemedes@gmail.com"
  },
  "dist": {
    "shasum": "a93c1b6e32ed814782a7998ad4b669b2e3d3957e",
    "tarball": "https://registry.npmjs.org/mongorito/-/mongorito-2.1.0.tgz"
  },
  "maintainers": [
    {
      "name": "vdemedes",
      "email": "sbioko@gmail.com"
    }
  ],
  "_npmOperationalInternal": {
    "host": "packages-12-west.internal.npmjs.com",
    "tmp": "tmp/mongorito-2.1.0.tgz_1463902378926_0.7016187575645745"
  },
  "directories": {},
  "_resolved": "https://registry.npmjs.org/mongorito/-/mongorito-2.1.0.tgz"
}
```

**Comment by vdemedes** [comment]
There's one: https://github.com/vdemedes/mongorito/blob/master/index.js.

**Comment by vdemedes** [comment]
Ok, huge thanks goes to @SamVerschueren for investigating this issue: https://github.com/SamVerschueren/npm-publish-index-test. Will republish the package today, thanks all for reporting it repeatedly!

**Comment by vdemedes** [comment]
I published v2.1.1 with a latest npm, please let me know if the issue is gone!

**Comment by SamVerschueren** [comment]
@vdemedes You have to publish with node 4 (or 5). As long as you are running on node >= 6, the issue remains.

**Comment by vdemedes** [comment]
@SamVerschueren yep, just realized it and republished with npm@2, thank you!

Looks like issue is gone. Thanks everyone!
